version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagementdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./TaskManagerAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=taskmanagementdb;Port=5432;Username=postgres;Password=postgres
      Jwt__Issuer: TaskManagerAPI
      Jwt__Audience: TaskManagerAPI-Clients
      Jwt__Key: dev-secret-key-change-me-please-very-long
      Jwt__ExpiresMinutes: 60
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:


