name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore TaskManagerAPI/TaskManagerAPI.csproj
      - name: Build
        run: dotnet build TaskManagerAPI/TaskManagerAPI.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish TaskManagerAPI/TaskManagerAPI.csproj --configuration Release --no-build -o out


